cleaning up repo
camaraproject/NumberVerification pull request #51
Opened 2023-07-26 12:50 UTC by DT-DawidWroblewski

#### What type of PR is this?
* cleanup

#### What this PR does / why we need it:

clean up repo

#### Which issue(s) this PR fixes:

Fixes #35
Fixes #29
Fixes #28

#### Special notes for reviewers:

cleans up repo

#### Changelog input

```
 archives MobileConnect definition
creates CAMARA reference to Mobile Connect
leaves CAMARA only API definition

```

#### Additional documentation

2023-07-27 08:55 UTC, diegogonmar requested changes
Thanks for the cleanup! 
Some additional comments:

- Mobile Connect files should be removed, not moved to archive. It's misleading to a reader to have a reference and then static content, more if archived info is from something not defined here but in a different standard. It would be also problematic to have obsolete information.
- Regarding references, although I proposed alternative wording, I still think that info does not help at all developers and may distract them. In any case reference should be only in .md, not in yaml.

Also some extra cleanup is needed:
This file should be removed --> 
https://github.com/camaraproject/NumberVerification/blob/main/code/API_definitions/README.MD
This folder is no longer needed, adds unneded folder hierarchy level: https://github.com/DT-DawidWroblewski/NumberVerification/tree/main/documentation/API_documentation/CAMARA
(info in the folder should be moved to upper level and empty folder removed)
This folder should be removed --> https://github.com/DT-DawidWroblewski/NumberVerification/tree/main/documentation/API_documentation/assets

2023-07-27 08:55 UTC, diegogonmar commented on code/API_definitions/number_verification.yaml
> +    This API derives from the GSMA Mobile Connect Account Takeover Protection specification [Mobile Connect Number Verify](https://www.gsma.com/identity/wp-content/uploads/2022/12/IDY.54-Mobile-Conne
Yaml should not include this info. This info should be in the .md files within API documentation. Yaml is API spec and has to stick to API Definition

2023-07-27 08:55 UTC, diegogonmar commented on documentation/API_documentation/CAMARA/NUMBER_VERIFICATION_API.md
> +It also makes it possible for a Service provider to verify the number itself by returning the phone number associated to the authenticated user's access token. This API derives from the GSMA Mobile C
Also please use references as in the rest of the document, pointing to a references chapter at the end of the doc.

2023-07-27 08:55 UTC, diegogonmar commented on documentation/API_documentation/README.MD
> +1. Download one of yaml file.
```suggestion
1. Download yaml file.
```

2023-07-27 08:55 UTC, diegogonmar commented on documentation/API_documentation/README.MD
> +CAMARA Number Verify API aims to deliver proof of device possession, that is attached to SIM card and MSISDN, using mobile network authentication. This API derives from the GSMA Mobile Connect Accoun
Same comment as above regarding proposed re-wording

2023-07-27 08:56 UTC, diegogonmar commented
@DT-DawidWroblewski happy to help, if you're ok I can upload a commit with the extra cleanup and my comments

2023-08-10 15:09 UTC, DT-DawidWroblewski commented on documentation/API_documentation/CAMARA/NUMBER_VERIFICATION_API.md
> +It also makes it possible for a Service provider to verify the number itself by returning the phone number associated to the authenticated user's access token. This API derives from the GSMA Mobile C
This is not true. Camara Number Verification API completely derives from "Number Verify" (www.numberverify.org explicitly stated on various presentaitons) that works on Mobile Connect Verified MSISDN spec.

2023-08-16 12:59 UTC, bigludo7 submitted a review, later dismissed

2023-08-31 14:25 UTC, diegogonmar commented on code/API_definitions/number_verification.yaml
> +    This API derives from the GSMA Mobile Connect Account Takeover Protection specification [Mobile Connect Number Verify](https://www.gsma.com/identity/wp-content/uploads/2022/12/IDY.54-Mobile-Conne
You're right @bigludo7, I didn't realize that. Suggestion then is to include the reference in the .yaml plus remove rest of documentation, meeting commonalities agreement

2023-09-01 13:56 UTC, closed without merging